### ISSUE TITLE
unexpected keyword argument 'repetition_penalty

### ISSUE THREAD

**Issue by noisyscott** [Softcatala/whisper-ctranslate2#58]
After upgrading to 0.2.9, whisper-ctranslate2 gives me this error when translating a .wav file
```
Traceback (most recent call last):
  File "/home/user/.local/bin/whisper-ctranslate2", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/src/whisper_ctranslate2/whisper_ctranslate2.py", line 554, in main
    result = transcribe.inference(
  File "/home/user/.local/lib/python3.10/site-packages/src/whisper_ctranslate2/transcribe.py", line 130, in inference
    segments, info = self.model.transcribe(
TypeError: WhisperModel.transcribe() got an unexpected keyword argument 'repetition_penalty'
```

**Comment by jordimas** [comment]
Thanks. You need faster-whisper>=0.8 

Type: pip install faster-whisper==0.9

and it should work

**Comment by noisyscott** [comment]
Thanks!  Can confirm that faster-whisper>=0.8 fixes the issue

**Comment by jordimas** [comment]
I will close this since I released a version which fixes it. Thanks for reporting it
